### ISSUE TITLE
The Gencord website is not working.

### ISSUE THREAD

**Issue by ThatGuyJamal** [Gencord/gencord#13]
Hello, I tried to go to the [website](https://js.org/302?gencord) to read the docs but it's not working.

**Comment by nerdthatnoonelikes** [comment]
Currently, we do not have that domain, https://github.com/Gencord/gencord.github.io, if you go to the docs repo and follow the readme instructions you can find more details on the library. Keep in mind that gencord is changing every few days so it might not be up to date. However https://github.com/Gencord/examples has a few examples you can use to get a sense of how the library works.
