### ISSUE TITLE
Guilds marked as undefined without "?" afterwards.

### ISSUE THREAD

**Issue by JustRadicalz** [Gencord/gencord#17]
I tried to recreate the "guildinfo.ts" command in the test directory but it guild was always showed up as undefined. Whenever I add a ? afterwards, the error goes away. But whenever I run !guildinfo everything is either marked as 0 or "undefined".

**Comment by eternalmoon1234** [comment]
Hi there, thanks for your issue. Can you send the code?

**Comment by JustRadicalz** [comment]
I deleted the code as I was just testing the Library. ANerdThatNoOneLikes was watching the stream at the time and he saw everything. Everything was working, it was just that guild had to be marked as optional. I even copy-pasted the code from the github and it still gave me the error.

**Comment by eternalmoon1234** [comment]
Hm no idea
