### ISSUE TITLE
Revive gencord

### ISSUE THREAD

**Issue by eternalmoon1234** [Gencord/gencord#19]
Revive time?

**Comment by nerdthatnoonelikes** [comment]
Yep I plan on working on it more later.

**Comment by Milo123459** [comment]
:bowtie:

**Comment by Milo123459** [comment]
Gencord is dead. It's official!
:bowtie: :neckbeard: :shipit: :octocat: :atom: :electron:

**Comment by eternalmoon1234** [comment]
it was dead and now its being revived kind of

**Comment by Milo123459** [comment]
no i like my message

**Comment by PraveshKunwar** [comment]
pls contribute :D

**Comment by Milo123459** [comment]
no u

**Comment by PraveshKunwar** [comment]
could restart if we wanted, but think we are too far in :(

**Comment by Milo123459** [comment]
may as well rewrite it

**Comment by eternalmoon1234** [comment]
no

**Comment by Milo123459** [comment]
wait rewrite to deno xd

**Comment by eternalmoon1234** [comment]
No

**Comment by PraveshKunwar** [comment]
thats a good idea tbh

**Comment by eternalmoon1234** [comment]
maybe but we're already far in

**Comment by eternalmoon1234** [comment]
idk

**Comment by PraveshKunwar** [comment]
I meannn true but

**Comment by PraveshKunwar** [comment]
We might as well restart, the whole project is a mess.

**Comment by PraveshKunwar** [comment]
idk tho

**Comment by Milo123459** [comment]
> We might as well restart, the whole project is a mess.

hahahhaaha @eternalmoon1234 someone agress with me HAHAHAHAH

**Comment by eternalmoon1234** [comment]
so uh nuke the repo? or

**Comment by eternalmoon1234** [comment]
i mean what are we going to do differently thats already here

**Comment by PraveshKunwar** [comment]
Let me know. I think its best if we restart now, and make a better lay out of what should be done.

**Comment by PraveshKunwar** [comment]
Idk, but I feel like we honestly don't know what we are doing lol, we should just start over and have a better plan but its up to you lol

**Comment by eternalmoon1234** [comment]
i think its cuz your new to the codebase, but yeah maybe we should restart

**Comment by eternalmoon1234** [comment]
https://imgur.com/a/AlcvBEY

**Comment by PraveshKunwar** [comment]
oof

**Comment by PraveshKunwar** [comment]
yeah lets just restart, probably better to do  it anyways. I don't think we need to delete the repo just delete all the files but again up to you

**Comment by PraveshKunwar** [comment]
honestly lets just leave it for now, we might as well continue ig

**Comment by eternalmoon1234** [comment]
yeah thatll be the better choice
