### ISSUE TITLE
Use JSDOC to document code.

### ISSUE THREAD

**Issue by PraveshKunwar** [Gencord/gencord#24]
Code needs to start being documented, using the official discord docs as well. Don't need to document interfaces or whatnot, but for the managers we need to start documenting it. 

https://jsdoc.app Here's the documentation for how to do it, its not that hard.

**Comment by Milo123459** [comment]
Won't happen most likely.

We'll stick to typings, and gencord is already messed up enough, as in no intellisense for JavaScript.

**Comment by eternalmoon1234** [comment]
There's no intellisense because of failures publishing, not in the actual code. When you test the code locally, there's intellisense for everything. We could use TypeDoc though.

**Comment by Milo123459** [comment]
> There's no intellisense because of failures publishing, not in the actual code. When you test the code locally, there's intellisense for everything. We could use TypeDoc though.

No intellisense when I compiled locally and required in another in another dir.

**Comment by eternalmoon1234** [comment]
Ok, then that's a problem with compiling

**Comment by eternalmoon1234** [comment]
There was an issue before where none of the actual code in src gets compiled into dist, which we should fix

**Comment by PraveshKunwar** [comment]
lets make a seperate issue for that ^
