### ISSUE TITLE
revivement

### ISSUE THREAD

**Issue by PraveshKunwar** [Gencord/gencord#27]
Yo duplicate of #19 but I think we should considering starting over tbh. I was wrong. The codebase is too confusing, its super messy, and a lot of the types are incorrect (mb on that one, _sorta_) lol. but I think we should seriously consider starting over, and maybe use deno instead if we want to rewrite?

**Comment by PraveshKunwar** [comment]
lmk what you guys think

**Comment by gautam-paranjape** [comment]
im down, but i suggest we dont completely nuke the repo, but instead delete all the files. that way the commits and stuff we did before will be preserved

**Comment by gautam-paranjape** [comment]
Also I am down for using Deno.

**Comment by PraveshKunwar** [comment]
Yeah I was thinking the same thing. Just delete all the files but preserve the repo itself. If you planning on doing it today I’ll start writing some guidelines on how to contribute and stuff tmrw , and a mini to do list that we can use to keep the code base organized.

**Comment by gautam-paranjape** [comment]
Ight sounds good, let's wait for Nerd to approve of this

**Comment by nerdthatnoonelikes** [comment]
I would be open to restarting over.

**Comment by gautam-paranjape** [comment]
Ok sounds good, let's talk over discord

**Comment by ThatGuyJamal** [comment]
Cool!

**Comment by gautam-paranjape** [comment]
revive time
